steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/sample:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/sample"]

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy to Kubernetes Engine
    args:
      - 'run'
      - '--filename'
      - deployment/staging/
      - '--location'
      - asia-south1
      - '--cluster'
      - cluster-2
