apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sample"
  namespace: staging
  labels:
    app: "sample"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sample"
  template:
    metadata:
      labels:
        app: "sample"
    spec:
      containers:
      - name: "sample"
        image: gcr.io/vanguard-20200519/sample:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace`
